-- =====================================================================
-- Carga inicial com os dados que já existiam nas planilhas.
-- Rode DEPOIS de schema.sql. Pode rodar novamente sem duplicar
-- (as inserções são condicionadas ao colaborador + data).
-- =====================================================================

-- ---------------------------------------------------------------------
-- CHAMADOS — as 18 respostas do formulário antigo, cruzadas com a
-- planilha de triagem (encaminhamento, responsável, situação e obs).
--
-- ATENÇÃO: a descrição do chamado da Daiane trazia as senhas de dois
-- estagiários em texto puro. Elas foram substituídas por
-- "[removida deste arquivo]" — este .sql tende a ir para o Git e a
-- tabela é legível por toda a equipe. Se essas senhas ainda estiverem
-- em uso, troque-as.
--
-- "resolvido_em" fica nulo nos chamados já resolvidos: a planilha não
-- registrava a hora da solução. Dos chamados resolvidos daqui pra frente
-- o gatilho grava a hora sozinho, e ela sai no CSV.
-- ---------------------------------------------------------------------
with novos (created_at, colaborador, email, natureza, equipamento, sistema, descricao, urgencia,
            encaminhado_para, reencaminhamento, responsavel_atendimento, triagem, resolvido, observacoes) as (
  values
    ('2026-08-31 11:21-03'::timestamptz,
     'Julia Baroli',
     'julia.baroli@rocharocha.adv.br',
     'Computador ou equipamento',
     'Notebook',
     null::text,
     'Armazenamento cheio decorrente de várias contas no notebook. Não tenho nada em dowloads, apenas onedrive e, ainda assim, o armazenamento continua sobrecarregado. Em razão disso, muitas das vezes não consigo abrir planilha, teams app (não carrega histórico nem manda mensagens, por isso utilizo na web) e impossibilidade de usar wpp web também.',
     'Média',
     'D&I',
     'Altatech',
     'Murilo',
     true,
     false,
     'Chamado aberto'),
    ('2026-08-31 14:06-03',
     'Gustavo Baleeiro - Rocha & Rocha Advogados',
     'gustavo.baleeiro@rocharocha.adv.br',
     'Computador ou equipamento',
     'Notebook',
     null,
     'Lentidão, dificuldade apra acessas sistemas, difucldade apra tarbalhar com pacote office.',
     'Alta',
     'D&I',
     'Altatech',
     'Murilo',
     true,
     false,
     'Chamado aberto'),
    ('2026-08-31 14:09-03',
     'Gustavo Baleeiro - Rocha & Rocha Advogados',
     'gustavo.baleeiro@rocharocha.adv.br',
     'Computador ou equipamento',
     'Notebook',
     null,
     'Semana passada solicitei para a Jennifer um chamado na altatech para formatar meu notebook. Ele já vem há um certo tempo apresentadao lentidão, travmento, principalmetne ao utilizar o pacote office, e os sitemas internos dele, como por exemplo ao salvar algum documento ou tentar imprimir. Ela havia me dito que solicitou com a altatech apra virem buscar o pc nesta quinta dia 03/09, tendo em vista que sexta não virei trabalhar e assim eles iriam ficar com o notebook e entregar na semana que vem. Gostaria de confirmar se isso foi solicitado, e caso não tenha sido, como daremos andamento.',
     'Alta',
     'D&I',
     'Altatech',
     'Murilo',
     true,
     false,
     'Chamado aberto'),
    ('2026-08-31 15:00-03',
     'Isabella Fragozo',
     'isabella@rocharocha.adv.br',
     'Rede ou internet',
     null,
     null,
     'Não consigo acessar a rede remotamente',
     'Média',
     'D&I',
     'Altatech',
     'Murilo',
     true,
     false,
     'Chamado aberto'),
    ('2026-09-01 10:42-03',
     'Ana Paula Fadel',
     'ana.fadel@rocharocha.adv.br',
     'Rede ou internet',
     null,
     null,
     'Estou de home office e não estou conseguindo acessar a rede. Ontem instalaram o VPN no meu computador, mas hoje ao tentar acessar a rede contava que o VPN estava desconectado. Tentei entrar com a senha do meu computador no app do VPN mas também não foi.',
     'Alta',
     'D&I',
     'Altatech',
     'Murilo',
     true,
     false,
     'Chamado aberto'),
    ('2026-09-01 14:13-03',
     'Daiane Leandro Ceu',
     'daiane.ceu@rocharocha.adv.br',
     'Acesso ou senha',
     null,
     null,
     E'Problema de acesso nas senhas dos dois novos estagiários:\n\nFernando Yokomizo - (Não está conseguindo acessar o Windows por senha inválida)\nlogin: fernando.yokomizo\nsenha [removida deste arquivo]\n\n\nEmilly\n(Não está conseguindo acessar o e-mail, senha inválida)\ne-mail: juridico10@rocharocha.adv.br\nsenha: [removida deste arquivo]',
     'Alta',
     'D&I',
     'Altatech',
     'Nathan',
     true,
     true,
     'Resolvido'),
    ('2026-09-01 15:03-03',
     'Gustavo Tamião',
     'gustavo.tamiao@rocharocha.adv.br',
     'Acesso ou senha',
     null,
     null,
     E'Gostaria de solicitar a criação de um usuario windows no AD para o Desenvolvimento, contendo acesso no ADV e ao pacote office.\n\nUm dos computadores windows terá logado este usuario e ficará disponível para a equipe do D&I utilizar quando necessário.',
     'Alta',
     'D&I',
     'Altatech',
     'Murilo',
     true,
     true,
     'Resolvido'),
    ('2026-09-01 16:45-03',
     'Priscila Campassi - Rocha & Rocha Advogados',
     'controladoria@rocharocha.adv.br',
     'Outro',
     null,
     null,
     'configurar o notebbok, que era da Kauana, para que seja colocado o nome da JULIANA, que começará dia 08/09 na controladoria',
     'Alta',
     'D&I',
     'Altatech',
     'Murilo',
     true,
     true,
     'Notebook Coletado pela Altatech'),
    ('2026-09-01 17:38-03',
     'Erick Sugimoto',
     'erick.sugimoto@rocharocha.adv.br',
     'Rede ou internet',
     null,
     null,
     'não tenho mais acesso à rede. quando eu clico nela aparece "a senha desta conta expirou".',
     'Alta',
     'D&I',
     'Altatech',
     'Murilo',
     true,
     true,
     'Reiniou e resolveu'),
    ('2026-09-02 09:04-03',
     'Cláudio Aparecido Medeiros',
     'claudio.medeiros@rocharocha.adv.br',
     'Outro',
     null,
     null,
     'Não estou conseguindo enviar documento para impressão.',
     'Média',
     'D&I',
     'Altatech',
     'Nathan',
     true,
     true,
     'Ok Murilo/Igor'),
    ('2026-09-02 10:22-03',
     'Arthur Francisco Fungaro Stringheta',
     'arthur@rocharocha.adv.br',
     'Rede ou internet',
     null,
     null,
     E'Desde ontem não estou conseguindo acessar a rede de arquivos.\nPor não trabalhar na sede, faço o acesso via VPN e, apesar de conseguir fazer conexão com a internet do escritório, não consigo fazer acesso à pasta de arquivos.\nJá desliguei e reiniciei o computador, mas o problema persiste.',
     'Alta',
     'D&I',
     'Altatech',
     'Murilo',
     true,
     false,
     'Chamado aberto'),
    ('2026-09-02 11:17-03',
     'Eduardo Lopes Carneiro',
     'eduardo.carneiro@rocharocha.adv.br',
     'Computador ou equipamento',
     'Notebook',
     null,
     'Meu notebook desliga sozinho do nada e nao tem como ligar novamente sem conectar no carregador, já passou por manutenção 2x, e a câmera não pega também',
     'Alta',
     'D&I',
     null,
     'Murilo',
     true,
     false,
     'Verificar com Murilo se foi realizado a Troca acho que não passou pra Altatech'),
    ('2026-09-03 10:00-03',
     'Amanda Brizola',
     'juridico10@rocharocha.adv.br',
     'Rede ou internet',
     null,
     null,
     'Minha rede não entra',
     'Alta',
     'D&I',
     'D&I -> Altatech',
     'Igor',
     true,
     true,
     'Ok Murilo/Igor'),
    ('2026-09-03 16:03-03',
     'Marcos Meneses',
     'marcos@rocharocha.adv.br',
     'Acesso ou senha',
     null,
     null,
     E'Preciso acessar a máquina da Júlia Dutra que se desligou do esc essa semana\n\nNão tenho a senha dela\n\nPodem ajudar?\n\nUrgência média, a depender do tempo de disponibilidade da máquina para terceiros.',
     'Média',
     'D&I',
     'Altatech',
     'Murilo',
     true,
     false,
     'Chamado aberto'),
    ('2026-09-03 16:54-03',
     'Ângela Honda - FINANCEIRO',
     'financeiro@rocharocha.adv.br',
     'Computador ou equipamento',
     'Impressora',
     null,
     'Não consigo imprimir documentos. Não consigo conexão com a impressora.',
     'Média',
     'Administrativo',
     'Altatech',
     'Igor',
     true,
     true,
     'Chamado aberto'),
    ('2026-09-03 17:01-03',
     'Priscilla Ortiz',
     'priscilla.ortiz@rocharocha.adv.br',
     'Computador ou equipamento',
     'Impressora',
     null,
     'Instalar a impressora colorida (que fica na sala do Diretor Victor) no meu notebook',
     'Média',
     'Administrativo',
     'Altatech',
     'Igor',
     true,
     true,
     'Complemento'),
    ('2026-09-03 17:03-03',
     'Priscilla Ortiz',
     'priscilla.ortiz@rocharocha.adv.br',
     'Computador ou equipamento',
     'Impressora',
     null,
     'Quando tento imprimir, a tela trava e preciso reiniciar o word. Nem abre a tela de impressão.',
     'Média',
     'Administrativo',
     'Altatech',
     'Igor',
     true,
     true,
     'Chamado aberto'),
    ('2026-09-08 10:56-03',
     'Anderson Silva',
     'anderson.silva@rocharocha.adv.br',
     'Sistema ou aplicativo interno',
     null,
     'pacote office e acesso ao B1',
     E'Os novos funcionários Walter Brandão e Eduardo Gabriel não estão conseguindo acessar o pacote office e acessar o B1\n\nemails: eduardo.gabriel@rocharocha.adv.br\n\nwalter.brandao@rocharocha.adv.br',
     'Alta',
     null,
     null,
     null,
     false,
     false,
     null)
)
insert into public.chamados
  (created_at, colaborador, email, natureza, equipamento, sistema, descricao, urgencia,
   encaminhado_para, reencaminhamento, responsavel_atendimento, triagem, resolvido, observacoes)
select n.* from novos n
where not exists (
  select 1 from public.chamados c
  where c.colaborador = n.colaborador and c.created_at = n.created_at
);

-- ---------------------------------------------------------------------
-- DESLIGAMENTOS
-- ---------------------------------------------------------------------
insert into public.desligamentos
  (colaborador, data_desligamento, usuario_windows, email_corporativo, email_backup,
   licencas_cancelar, recolhimento_maquina, recolhimento_mouse_teclado)
select * from (values
  ('RAQUEMILLY QUEREN MORAES DE ALMEIDA', '2026-09-02'::date, 'raquemilly.almeida', 'raquemilly.almeida@rocharocha.adv.br', 'marcos@rocharocha.adv.br',      'Sim', 'Recolhido', 'Recolhido'),
  ('LARA DE PAIVA OMENA',                 '2026-09-01'::date, 'lara.paiva',         'lara.paiva@rocharocha.adv.br',         'henrique.souza@rocharocha.adv.br','Sim', 'Recolhido', 'Recolhido'),
  ('MARINA PEREIRA TICIANELLI',           '2026-08-31'::date, null,                 'juridico12@rocharocha.adv.br',         'juridico19@rocharocha.adv.br',   'Sim', 'Recolhido', 'Recolhido'),
  ('JENNIFER PLACIDO BATISTA',            '2026-08-31'::date, null,                 'administrativo@rocharocha.adv.br',     'financeiro@rocharocha.adv.br',   'Sim', 'Recolhido', 'Recolhido'),
  ('JULIA VIEIRA DUTRA',                  '2026-08-31'::date, 'julia.dutra',        'julia.dutra@rocharocha.adv.br',        'marcos@rocharocha.adv.br',       'Sim', 'Recolhido', 'Recolhido'),
  ('LUCAS EIDI MATSNURA',                 '2026-08-31'::date, 'lucas.matsnura',     'lucas.matsnura@rocharocha.adv.br',     'marcos@rocharocha.adv.br',       'Sim', 'Recolhido', 'Recolhido'),
  ('JHONATAS LUIZ MOREIRA DE PAULA FILHO','2026-08-05'::date, 'jhonattan.silva',    'jhonattan.silva@rocharocha.adv.br',    'juliacastro@rocharocha.adv.br',  'Sim', 'Recolhido', 'Recolhido'),
  ('KAUANA NIEUWENHOFF FRAGA',            '2026-08-03'::date, null,                 'documentos01@rocharocha.adv.br',       'documentos01@rocharocha.adv.br', 'Não', 'Recolhido', 'Recolhido')
) as v(colaborador, data_desligamento, usuario_windows, email_corporativo, email_backup,
       licencas_cancelar, recolhimento_maquina, recolhimento_mouse_teclado)
where not exists (
  select 1 from public.desligamentos d
  where d.colaborador = v.colaborador and d.data_desligamento = v.data_desligamento
);

-- ---------------------------------------------------------------------
-- ADMISSÕES
-- ---------------------------------------------------------------------
insert into public.admissoes
  (colaborador, data_admissao, divide_maquina, maquina, mouse_teclado, monitor,
   solicitacao_altatech, numero_chamado, providenciar_maquina, providenciar_equipamentos)
select * from (values
  ('Gabriel Shawarski de Mello Montanha',  '2026-09-17'::date, 'Não', '360', '129', '383',      'Em andamento', '#0926-000166', 'Formatação', 'Concluído'),
  ('Eduardo Gabriel Guilherme dos Santos', '2026-09-08'::date, 'Não', '388', '71',  '270',      'Em andamento', '#0926-000166', 'Formatação', 'Concluído'),
  ('Juliana Santos Alves',                 '2026-09-08'::date, 'Não', '382', '55',  'R&R 0242', 'Em andamento', '#0926-000166', 'Formatação', 'Concluído'),
  ('Walter Brandão da Silva Neto',         '2026-09-08'::date, 'Não', '301', '103', 'R&R 0389', 'Em andamento', '#0926-000166', 'Formatação', 'Concluído')
) as v(colaborador, data_admissao, divide_maquina, maquina, mouse_teclado, monitor,
       solicitacao_altatech, numero_chamado, providenciar_maquina, providenciar_equipamentos)
where not exists (
  select 1 from public.admissoes a
  where a.colaborador = v.colaborador and a.data_admissao = v.data_admissao
);
